perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0001.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0002.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0003.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0004.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0005.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0006.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0007.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0008.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0009.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0010.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0011.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0012.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0013.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0014.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0015.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0016.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0017.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0018.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0019.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0020.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0021.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0022.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0023.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0024.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0025.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0026.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0027.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0028.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0029.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0030.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0031.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0032.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0033.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0034.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0035.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0036.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0037.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0038.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0039.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0040.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0041.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0042.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0043.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0044.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0045.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0046.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0047.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0048.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0049.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0050.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0051.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0052.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0053.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0054.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0055.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0056.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0057.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0058.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0059.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0060.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0061.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0062.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0063.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0064.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0065.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0066.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0067.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0068.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0069.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0070.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0071.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0072.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0073.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0074.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0075.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0076.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0077.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0078.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0079.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0080.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0081.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0082.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0083.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0084.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0085.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0086.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0087.xml	kb_to_wiki_id/
perl resolve_kb_wikipedia_ids.pl	data/	kb_part-0088.xml	kb_to_wiki_id/

